
name: github
on: push 
jobs:
    first_workflow:
        runs-on: ubuntu-latest  
        steps:
            - name: Welcome message
              run: echo welcome message
           
            - name: checkout action
              uses: actions/checkout@v4

            - name : install dependencies
              run: sudo apt-get install cowsay -y 
           
            - name: generate ASCII
              run: cowsay  -f dragon "run" >> dragon.txt

            - name: Test files 
              run: grep -I "dragon" dragon.txt 

            - name: list files
              run: ls 

            - name: Read file
              run: cat README.md