name: github

on: push

jobs:
    first_workflow:
        runs-on: ubuntu-latest  
        steps:
          - name: checkout action
            uses: actions/checkout@v4

          - name: list files
            run: ls -ltra
          
          - name: chmod 
            run: chmod +x README.sh

          - name: execute 
            run: ./README.sh
            
