name: github

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest  
        steps:
          - name: checkout action
            uses: actions/checkout@v4
          
          - name: chmod 
            run: chmod +x README.sh

          - name: execute 
            run: ./README.sh
          
          - name: upload artfact
            uses: actions/upload-artifact@v3
            with: 
               name: dragon-text-file
               path: dragon.txt

    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
          - name: download artifact
            uses: actions/download-artifact@v3
            with:
             name: dragon-text-file
          - name: test if file exists
            run: grep -i "dragon" dragon.txt
    
    deploy_job:
        needs: [ build_job,test_job ] 
        runs-on: ubuntu-latest 
        steps:
          - name: download artifact
            uses: actions/download-artifact@v3
            with:
              name: dragon-text-file
          - name: deploy
            run: cat dragon.txt
            
