name: github

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest  
        steps:
          - name: checkout action
            uses: actions/checkout@v4
          
          - name: chmod 
            run: chmod +x README.sh

          - name: execute 
            run: ./README.sh
          
          - name: sleep for 30 seconds
            run: sleep 30 
    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
           - name: test if file exists
             run: grep -i "dragon" dragon.txt
    
    deploy_job:
        needs: [ build_job,test_job ] 
        runs-on: ubuntu-latest 
        steps:
           - name: deploy
             run: cat dragon.txt
            
