name: github

on: push

jobs:
    first_workflow:
        runs-on: ubuntu-latest  
        steps:
          - name: Welcome message
            run: echo welcome message
           
          - name: checkout action
            uses: actions/checkout@v4

          - name: list files
            run: |
             ls

          - name: change permission
            run : chmod +x bharatei/githubactions/.github/new.sh
  
          - name: run script 
            run: ./new.sh
            
          - name: check
            run: ls -ltra 
