name: github

on: push

jobs:
    first_workflow:
        runs-on: ubuntu-latest  
        steps:
          - name: Welcome message
            run: echo welcome message
           
          - name: checkout action
            uses: actions/checkout@v4

          - name: list files
            working-directory: workflows
            run: ls
  
          - name: run script 
            run: ./new.sh
            
